version: '3.1'

volumes:
  postgres_data:

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: workstream
      POSTGRES_USER: workstream
      POSTGRES_DB: workstream
      PGDATA: /var/lib/postgresql/data/workstream
    volumes:
      - postgres_data:/var/lib/postgresql/data/workstream
    ports:
      - 5432:5432
